Feat/#59 타입수정, 타입에 맞게 코드수정
hyejungg/ai-news-noti-bot pull request #61
Opened 2024-11-08 11:07 UTC by jongwoo328

Close #59 

딱히 추가로 설명할 건 없는 것 같고
타입 변경하면서 관련코드도 같이 변경되었는데 문제 없는지 확인해주세요~

2024-11-08 12:35 UTC, hyejungg requested changes
정말정말 고생 많으셨습니다!! 
덕분에 저도 코드도 이해하고 생각을 정리하는 시간이 됐어요 .. !! 

db에서 메세지 가져오는 로직이나 일부 파일에서 사용하지 않는 import 들이 많긴 한데 이런건 추후에 개발할 때 반영 되어도 괜찮을 것 같아서 해당 PR 에서 추가로 수정해주셨으면 하는 부분만 코멘트로 남겼습니다!

고생 많으셨습니다 :D 👍

2024-11-08 12:35 UTC, hyejungg commented on news-scraper-agent/models/site.py
> +from datetime import datetime
이것도 import 삭제하고 해당 파일에 EOF 추가 부탁드립니다! 

<img width="318" alt="image" src="https://github.com/user-attachments/assets/43195527-ada8-4de0-88fb-de897c97c9a7">
---

추가로 utils/time_utils.py 에서 `get_datetime_kst()` 여기서 `datetime.utcnow()` 는 곧 삭제될 메서드라고 ide에서 떠서 검색해보니 
이렇게 바꿔주실 수 있을까요?
```python
from datetime import timezone, datetime
import pytz


def get_datetime_kst():
    utc_now = datetime.now(timezone.utc)
    kst = pytz.timezone("Asia/Seoul")
    kst_now = utc_now.replace(tzinfo=pytz.utc).astimezone(kst)
    return kst_now
```
[참고](https://www.andreagrandi.it/posts/python-now-time-to-migrate-from-utcnow/)

2024-11-08 12:35 UTC, hyejungg commented on news-scraper-agent/graph/build_graph.py
> +    def process_site(state: State) -> SiteState:
`def process_site() -> SiteState:` 로 바꿔도 될 것 같습니다!

2024-11-08 12:35 UTC, hyejungg commented on news-scraper-agent/graph/state.py
> +from typing import Any, TypedDict
코드 내려받아보니 이건 더이상 사용하지 않는 것 같습니다! import 삭제해주세요!

2024-11-08 12:35 UTC, hyejungg commented on news-scraper-agent/graph/build_graph.py
>  # LLM = ChatOpenAI(model_name=config.MODEL_NAME)
저번에 LLM 변수 llm으로 바꾸신다고 하셨던 것 같은데 맞나요 ?!

2024-11-08 12:35 UTC, hyejungg commented on news-scraper-agent/graph/state.py
> +type ParserResult = dict[str, str]
😲👍  되게 ts 같군요!

2024-11-08 12:35 UTC, hyejungg commented on news-scraper-agent/graph/build_graph.py
> +import copy
이거는 사용되지 않는 것 같아서 지워주셔도 될 것 같습니다!

2024-11-08 12:35 UTC, hyejungg commented on news-scraper-agent/service/site_service.py
> +    ]
😲👍 여기선 dto 를 이렇게 바꾸는군요

2024-11-09 06:13 UTC, jongwoo328 commented on news-scraper-agent/service/site_service.py
> +    ]
원래 `**` 하나로 될텐데 시간컬럼이 없는데이터와 pydantic validation이 만나서 좀 복잡해졌네요 🤣

2024-11-09 06:16 UTC, jongwoo328 commented on news-scraper-agent/graph/state.py
> +type ParserResult = dict[str, str]
3.12에 생긴 나름 최신기능이에요 ㅎㅎ

2024-11-09 06:18 UTC, jongwoo328 commented on news-scraper-agent/graph/build_graph.py
> +    def process_site(state: State) -> SiteState:
이건 실제로 저 함수에 인자가 들어오더라고요? 근데 랭체인에서 타입 체크를 해서 선언이 안되어있으면 에러가 발생해서 사용은 안하지만 추가했습니다

2024-11-11 00:03 UTC, hyejungg approved these changes

2024-11-11 08:41 UTC, merged